### ISSUE TITLE
New master/version

### ISSUE THREAD

**Issue by KvanSteijn** [matriphe/php-iso-639#4]
Hello, when are you creating new master with version tag?

**Comment by matriphe** [comment]
Hello, 

This already has a version 1.0 tag. Can you be more specific?

**Comment by KvanSteijn** [comment]
I know, but the last changes in your repo doesn't have new version tag. I need version tag for composer.

**Comment by matriphe** [comment]
Ah, thanks for your reminder.

I've just push new version 1.1.
