### ISSUE TITLE
The pt-BR is not working.

### ISSUE THREAD

**Issue by mullernato** [matriphe/php-iso-639#6]
The pt-BR code is not working.

Reference codes:
http://www.localeplanet.com/icu/iso639.html

**Comment by matriphe** [comment]
can you tell me more what is not working? any example?

**Comment by mullernato** [comment]
if use 

`echo $iso->languageByCode1('pt-BR');`

not returns  Brazilian Portuguese

**Comment by mullernato** [comment]
Suggestion
https://github.com/mullernato/php-iso-639/tree/patch-1

**Comment by MrPetovan** [comment]
Unfortunately `pt-BR` isn't part of ISO-639 but [IETF BCP 47](https://en.wikipedia.org/wiki/IETF_language_tag) which is a completely different standard. You might want to check this library for a BCP 47 implementation: https://github.com/whitecube/lingua
